import { Toaster } from '@/components/ui/toaster'
import SessionProvider from '@/providers/SessionProvider'
import ThemeProvider from '@/providers/ThemeProvider'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'

import '../globals.css'
import { inter } from '@/providers/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Toaster />
          <SessionProvider session={session}>{children}</SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
